# Constants used in SageMaker
# TODO: Move these to sagemaker-containers

# Resource related constants
SM_CURRENT_HOST = 'SM_CURRENT_HOST'
SM_HOSTS = 'SM_HOSTS'

# Data related constants
SM_CHANNEL_TRAIN = 'SM_CHANNEL_TRAIN'
SM_CHANNEL_VALIDATION = 'SM_CHANNEL_VALIDATION'
SM_MODEL_DIR = 'SM_MODEL_DIR'

# Training constants
SM_INPUT_TRAINING_CONFIG_FILE = "SM_INPUT_TRAINING_CONFIG_FILE"
SM_INPUT_DATA_CONFIG_FILE = "SM_INPUT_DATA_CONFIG_FILE"
