# the tag z is dependent on py27, py35 and cpu, gpu. one of the above images
# FROM 683313688378.dkr.ecr.us-east-1.amazonaws.com/sagemaker-xgboost:1.3-1
FROM python:3.8-slim

COPY tanpv-requirements.txt /src/tanpv-requirements.txt

RUN pip3 install --force-reinstall pip==20.0.2
RUN pip install -r /src/tanpv-requirements.txt

# COPY final_feature_processing.py /src/final_feature_processing.py

COPY training.py /src/training.py

ENTRYPOINT ["python3", "/src/training.py"]