version: 0.2

phases:
  pre_build:
    commands:
    - echo Logging in to Amazon ECR...
    - $(aws ecr get-login --no-include-email --region $AWS_DEFAULT_REGION)
  build:
    commands:
    - echo Build started on `date`
    - echo Building the Docker image...
    - docker build -t xgboost-container-base:0.90-2-cpu-py3 -f docker/0.90-2/base/Dockerfile.cpu .
    - python setup.py bdist_wheel --universal
    - aws s3 cp s3://codepipeline-us-west-2-smdebug-binaries/smdebug/smdebug-0.4.12-py2.py3-none-any.whl .  # TODO-reinvent-2019: remove and replace with pip install in dockerfile
    - docker build -t preprod-xgboost-container:0.90-2-cpu-py3 -f docker/0.90-2/final/Dockerfile.cpu .
    - docker tag preprod-xgboost-container:0.90-2-cpu-py3 515193369038.dkr.ecr.us-west-2.amazonaws.com/sagemaker-xgboost:0.90-2-cpu-py3
  post_build:
    commands:
    - echo Build completed on `date`
    - echo Pushing the Docker image...
    - docker push 515193369038.dkr.ecr.us-west-2.amazonaws.com/sagemaker-xgboost:0.90-2-cpu-py3
