version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.7
      docker: 17
  pre_build:
    commands:
    - echo Pre-build started on `date`
    - echo Installing dependencies...
    - curl -LO http://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh
    - bash Miniconda3-latest-Linux-x86_64.sh -bfp /miniconda3
    - export PATH=/miniconda3/bin:${PATH}
    - conda install python=3.7
    - conda update -y conda
    - conda install -y 'requests<2.21'  # sagemaker-python-sdk requires requests<2.21
    - conda install tbb==2020.2
    - python3 -m pip install pip==20.1  # The new pip denpendency resolver in 20.2+ can't resolve 1.0-1 and 0.90 dependencies
    - python3 -m pip install .[test]
  build:
    commands:
    - echo Build started on `date`
    - echo Docker login...
    - docker login -u $dockerhub_username -p $dockerhub_password
    - echo Building the Docker image...
    - docker build -t xgboost-container-base:$FRAMEWORK_VERSION-cpu-py3 -f docker/$FRAMEWORK_VERSION/base/Dockerfile.cpu .
    - python3 setup.py bdist_wheel --universal
    - docker build -t preprod-xgboost-container:$FRAMEWORK_VERSION-cpu-py3 -f docker/$FRAMEWORK_VERSION/final/Dockerfile.cpu .
    - echo Running tox...
    - printf "FROM preprod-xgboost-container:$FRAMEWORK_VERSION-cpu-py3\nADD . /app\nWORKDIR /app\nRUN python3 -m pip install .[test]" > Dockerfile.test
    - docker build -t test-xgboost-container -f Dockerfile.test .
    - docker run --rm -t test-xgboost-container sh -c 'pytest --cov=sagemaker_xgboost_container --cov-fail-under=60 test/unit'
    - docker run --rm -t test-xgboost-container sh -c 'flake8 setup.py src test'
    - echo Running container tests...
    - pytest test/integration/local --docker-base-name preprod-xgboost-container --tag $FRAMEWORK_VERSION-cpu-py3 --py-version 3 --framework-version $FRAMEWORK_VERSION
    - docker tag preprod-xgboost-container:$FRAMEWORK_VERSION-cpu-py3 $SM_ALPHA.dkr.ecr.us-west-2.amazonaws.com/sagemaker-xgboost:$FRAMEWORK_VERSION-cpu-py3
    - docker tag preprod-xgboost-container:$FRAMEWORK_VERSION-cpu-py3 $SM_ALPHA.dkr.ecr.us-west-2.amazonaws.com/sagemaker-xgboost:$FRAMEWORK_VERSION
  post_build:
    commands:
    - echo Build completed on `date`
    - |
      case $CODEBUILD_WEBHOOK_EVENT in
        PULL_REQUEST_MERGED)
          echo Logging in to Amazon ECR...
          $(aws ecr get-login --no-include-email --region $AWS_DEFAULT_REGION)
          echo Pushing the Docker image...
          docker push $SM_ALPHA.dkr.ecr.us-west-2.amazonaws.com/sagemaker-xgboost:$FRAMEWORK_VERSION-cpu-py3 | grep -v -E "[0-9]{12}.dkr.ecr.\S+.amazonaws.com"
          docker push $SM_ALPHA.dkr.ecr.us-west-2.amazonaws.com/sagemaker-xgboost:$FRAMEWORK_VERSION | grep -v -E "[0-9]{12}.dkr.ecr.\S+.amazonaws.com"
          ;;
        PULL_REQUEST_CREATED | PULL_REQUEST_UPDATED | PULL_REQUEST_REOPENED)
          echo Logging in to Amazon ECR...
          $(aws ecr get-login --no-include-email --region $AWS_DEFAULT_REGION)
          echo Pushing the Docker image...
          # pushes test tag for manual verification, requires cleanup in ECR every once in a while though
          TEST_TAG=$SM_ALPHA.dkr.ecr.us-west-2.amazonaws.com/sagemaker-xgboost:${FRAMEWORK_VERSION}-cpu-py3-test
          docker tag preprod-xgboost-container:$FRAMEWORK_VERSION-cpu-py3 ${TEST_TAG}
          docker push ${TEST_TAG} | grep -v -E "[0-9]{12}.dkr.ecr.\S+.amazonaws.com"
          ;;
        *)
          echo Undefined behavior for webhook event type $CODEBUILD_WEBHOOK_EVENT
          ;;
      esac
